apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pay-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: pay-gateway.pay.pjoc.pub
      http:
        paths:
          - path: /
            backend:
              serviceName: pay-gateway
              servicePort: "grpc-gateway"
          - path: /v1/web/
            backend:
              serviceName: pay-gateway
              servicePort: "web"